CREATE DATABASE IF NOT EXISTS Score;

USE Score;

CREATE TABLE IF NOT EXISTS score (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tiempo INT NOT NULL,
  puntos INT NOT NULL,
  fecha DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  nombre VARCHAR(80) NOT NULL
);